// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMV2mHhvOFNmJT_7Zm2EnBydpgOBddjoM',
    appId: '1:138568097083:web:95b059c587bd2a39d1ab1e',
    messagingSenderId: '138568097083',
    projectId: 'gemicates-test',
    authDomain: 'gemicates-test.firebaseapp.com',
    storageBucket: 'gemicates-test.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGr0hrB5_6RJX_oO79-g_MnNaAjzBgA8U',
    appId: '1:138568097083:android:91cc59b30920fc12d1ab1e',
    messagingSenderId: '138568097083',
    projectId: 'gemicates-test',
    storageBucket: 'gemicates-test.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqI4kJPoIni36_cCGzhvy06egikoyUeDk',
    appId: '1:138568097083:ios:e8a6e226d37f2f3ad1ab1e',
    messagingSenderId: '138568097083',
    projectId: 'gemicates-test',
    storageBucket: 'gemicates-test.appspot.com',
    iosBundleId: 'com.example.gemicatesTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqI4kJPoIni36_cCGzhvy06egikoyUeDk',
    appId: '1:138568097083:ios:e8a6e226d37f2f3ad1ab1e',
    messagingSenderId: '138568097083',
    projectId: 'gemicates-test',
    storageBucket: 'gemicates-test.appspot.com',
    iosBundleId: 'com.example.gemicatesTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMV2mHhvOFNmJT_7Zm2EnBydpgOBddjoM',
    appId: '1:138568097083:web:079efaa3790d0e7dd1ab1e',
    messagingSenderId: '138568097083',
    projectId: 'gemicates-test',
    authDomain: 'gemicates-test.firebaseapp.com',
    storageBucket: 'gemicates-test.appspot.com',
  );

}